
        <div class="row">
            <div class="col-md-6">
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
<!--                      <div class="col-md-8">Módulo
                    <strong class="text-uppercase"> <?php echo $a->modulo?></strong>
                      </div>
                      <div class="col-md-2 text-right">
                      </div>-->
                      <div class="col-md-2 text-right offset-md-10">
                          <a class="btn btn-primary " href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                  <?php echo Form::hidden("a.id")?>
                <div class="card-body">
                    
                  <?php View::content()?>
                  <div class="form-group">
                    <label for="a_perfil"> Módulo</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_perfil"> Nombre del Perfil</label>
                    <?php echo Form::input("text","a.perfil", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <?php Flash::error("Confirma borrar este Perfil, Por favor, Confirmar")?>
                <div class="card-footer text-right">
                    <div class="row">
                        <div class="col-md-2 offset-md-10 text-right">
                          <button type="submit" class="btn btn-danger btn-block">Si, Borrar</button>
                        </div>
                    </div>
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
  
</script>


