
        <div class="row">
            <div class="col-md-6">
                
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
<!--                      <div class="col-md-8">Módulo
                    <strong class="text-uppercase"> <?php //echo $a->modulo?></strong>
                      </div>-->
                      <div class="col-md-10 text-right">
                      </div>
                      <div class="col-md-2 text-right">
                          <a class="btn btn-primary" href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.id")?>
                    <?php echo Form::hidden("a.modulo_id")?>
                  <div class="form-group">
                    <label for="a_perfil"> Módulo</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_perfil"> Nombre del Perfil</label>
                    <?php echo Form::input("text","a.perfil", ' class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2 offset-md-10 text-right">
                            <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-save"></i>  Modificar</button>
                        </div>
                    </div>
                </div>
              </form>
            </div>
           
            </div>
        </div>
        <!-- /.row -->

<script>
  $(function () {

  });
</script>


