
        <div class="row">
            <div class="col-md-8">
                
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
                      <div class="col-md-2 text-right offset-md-10">
                          <a class="btn btn-primary" href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.perfil_id")?>
                  <div class="form-group">
                    <label for="a_modulo"> Módulo Seleccionado</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_modulo"> Perfil Seleccionado</label>
                    <?php echo Form::input("text","a.perfil", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_controlador_id"> Seleccione Controlador</label>
                    <?php echo Form::dbSelectCripto("a.controlador_id", NULL,array("controlador","combo_controladorXperfil",array("perfil_id"=>$a->perfil_idx) ),NULL,'required class="form-control"')?>
                  </div>
                  <div class="form-group">
                    <label for="a_accion_id"> Seleccione Controlador</label>
                    <?php echo Form::select("a.accion_id", array(),' class="form-control" required')?>
                  </div>
                    
<!--                  <div class="form-group">
                    <label for="a_controlador"> Nombre de la Acción</label>
                    <?php //echo Form::input("text","a.accion", ' class="form-control" maxlength="45" placeholder="Ingrese la acción del controlador" ')?>
                  </div>-->
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2 offset-md-10 text-right">
                            <button type="submit" class="btn btn-primary  btn-block"><i class="fa fa-save"></i>  Registrar</button>
                        </div>
                    </div>
                </div>
              </form>
            </div>
                
           </div>
        </div>
        <!-- /.row -->
<script>
    $(document).ready(function (){
        ver_acciones();
       
        $("#a_controlador_id").change(function (){
            ver_acciones();
        });
    });
    
    function ver_acciones()
    {
        var controlador_id = $("#a_controlador_id").val();
        
        var url = "<?php echo PUBLIC_PATH?>../../sysaccion/ajax_combo_norepeat";
        var datos = {"controlador_id": controlador_id};
        console.log(controlador_id);
        $.post(url,datos,function(r){
            console.log(r);
            $("#a_accion_id").html(r);
        });
        
    }
    
    
  $(function () {

  });
</script>

