
        <div class="row">
            <div class="col-md-8">
                
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
<!--                      <div class="col-md-2">Módulo</div>
                      <div class="col-md-5 h4"><?php echo $a->modulo?></div>-->
                      <div class="col-md-2 text-right offset-md-10">
                          <a class="btn btn-primary" href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.modulo_id")?>
                  <div class="form-group">
                    <label for="a_modulo"> Módulo Seleccionado</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_controlador_id"> Perfil Seleccionado</label>
                    <?php echo Form::dbSelectCripto("a.perfil_id", NULL,array("perfil","combo_perfilesXmodulo",array("modulo_id"=>$a->id)),NULL,' class="form-control"')?>
                  </div>
                    
                  <div class="form-group">
                    <label for="a_controlador"> Nombre del Controlador</label>
                    <?php echo Form::input("text","a.controlador", ' class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2 offset-md-10 text-right">
                            <button type="submit" class="btn btn-primary  btn-block"><i class="fa fa-save"></i>  Registrar</button>
                        </div>
                    </div>
                </div>
              </form>
            </div>
                
           </div>
        </div>
        <!-- /.row -->

<script>
  $(function () {

  });
</script>


