
        <div class="row">
            <div class="col-md-6">
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
                      <div class="col-md-12 text-right">
                          <a class="btn btn-primary" href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                  <?php echo Form::hidden("a.id")?>
                    <?php echo Form::hidden("a.modulo_id")?>
                <div class="card-body">
                  <?php View::content()?>
                  <div class="form-group">
                    <label for="a_modulo"> Módulo Seleccionado</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_modulo"> Perfil Seleccionado</label>
                    <?php echo Form::input("text","a.perfil", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
<!--                  <div class="form-group">
                    <label for="a_controlador_id"> Perfil Seleccionado</label>
                    <?php echo Form::dbSelectCripto("a.perfil_id", 
                                                    NULL,
                                                    array("perfil","combo_perfilesXmodulo",array("modulo_id"=>$a->modulo_idx)),
                                                    NULL,' class="form-control"',$a->perfil_id)?>
                  </div>-->
                  <div class="form-group">
                    <label for="a_controlador"> Nombre del Controlador</label>
                    <?php echo Form::input("text","a.controlador", ' disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <?php Flash::error("Confirma borrar este Controlador  de este Módulo, Por favor, Confirmar")?>
                <div class="card-footer text-right">
                  <button type="submit" class="btn btn-danger">Si, Borrar</button>
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
  
</script>


