
        <div class="row">
            <div class="col-md-10">
<div class="card card-secondary">
              <div class="card-header text-right">
                  <a class="btn btn-primary" href="<?php echo $link_add?>"> <i class="fa fa-plus"></i> Nuevo Módulo</a>
              </div>
                  <?php View::content()?>
                <div class="card-body">
<table id="example" class="table table-striped table-bordered dt-responsive nowrap">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Módulo</th>
                <th>Menú</th>
                <th>Descripción</th>
                <th>Icono</th>
                <th>Precio</th>
                <th>Privado</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($lista as $value):?>
            <tr>             
                <td>
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="<?php echo $link_edit. Crypto::e($value->id)?>"><i class="fa fa-edit text-indigo"></i> Modificar</a>
    <a class="dropdown-item" href="<?php echo $link_del.Crypto::e($value->id)?>"><i class="fa fa-trash text-danger"></i> Borrar</a>
  </div>
</div>                </td>
                <td><?php echo $value->modulo?></td>
                <td><?php echo $value->menu?></td>
                <td>
                    <div class="text-break " style="text-overflow: ellipsis; overflow: hidden;max-width: 200px;">
                        <?php echo $value->descripcion?>
                    </div>
                </td>
                <td>
                    <?php if($value->logo){?>
                    <i class="text-info <?php echo $value->logo?> fa-2x "></i>
                    <?php }?>
                    <?php echo $value->logo?>
                </td>
                <td><?php echo $value->precio?></td>
                <td><?php echo Modulo::$PRIVADO[$value->privado]?></td>
            </tr>
            <?php endforeach;?>
        </tbody>
</table>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <!--<button type="submit" class="btn btn-primary">Registrar</button>-->
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
  $(function () {
    $("#example").DataTable({
      "responsive": true,
      "bInfo" : false,
       "paging": false,
      //"autoWidth": false,
    });
//    $('#example2').DataTable({
//      "paging": true,
//      "lengthChange": false,
//      "searching": false,
//      "ordering": true,
//      "info": true,
//      "autoWidth": false,
//      "responsive": true,
//    });
  });
</script>



