
        <div class="row">
            <div class="col-md-8">
                
            <div class="card card-secondary">
              <div class="card-header">
                  <div class="row">
                      <div class="col-md-2 text-right offset-md-10">
                          <a class="btn btn-primary" href="<?php echo $link_volver?>"><i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                  </div>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.id")?>
                    <?php echo Form::hidden("a.perfil_id")?>
                  <div class="form-group">
                    <label for="a_modulo"> Módulo Seleccionado</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Módulo" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_modulo"> Perfil Seleccionado</label>
                    <?php echo Form::input("text","a.perfil", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Perfil" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_controlador"> Controlador</label>
                    <?php echo Form::input("text","a.controlador", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_accion"> Acción Seleccionada</label>
                    <?php echo Form::input("text","a.accion", 'disabled class="form-control" maxlength="45" placeholder="Ingrese la Accion" ')?>
                  </div>
                    
                  <div class="form-group">
                    <label for="a_texto"> Texto Menú</label>
                    <?php echo Form::input("text","a.texto", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el texto" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_icono"> Ícono Font Awesome</label>
                    <?php echo Form::input("text","a.icono", 'disabled  class="form-control" maxlength="45" placeholder="Nombre del ícono Font Awesome" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_color"> Color</label>
                    <?php echo Form::input("text","a.color", 'disabled  class="form-control" maxlength="45" placeholder="Color del ícono bootstrap" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_posicion">Posición</label>
                    <?php echo Form::input("number","a.posicion", 'disabled  class="form-control" placeholder="Posición del Menú" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <?php Flash::error("¿Realmente desea borrar este menú? Por favor, Confirme")?>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-2 offset-md-10 text-right">
                            <button type="submit" class="btn btn-danger  btn-block"><i class="fa fa-question"></i> Si, Borrar</button>
                        </div>
                    </div>
                </div>
              </form>
            </div>
                
           </div>
        </div>
        <!-- /.row -->
<script>
</script>

